/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects.index'
import { Route as AuthProjectsVerifyRouteImport } from './routes/_auth/projects..verify'
import { Route as AuthProjectsIdIndexRouteImport } from './routes/_auth/projects.$id.index'
import { Route as AuthProjectsIdProductsPidRouteImport } from './routes/_auth/projects.$id.products.$pid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsVerifyRoute = AuthProjectsVerifyRouteImport.update({
  id: '/projects/verify',
  path: '/projects/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIdIndexRoute = AuthProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIdProductsPidRoute =
  AuthProjectsIdProductsPidRouteImport.update({
    id: '/projects/$id/products/$pid',
    path: '/projects/$id/products/$pid',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/verify': typeof AuthProjectsVerifyRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/projects/$id/': typeof AuthProjectsIdIndexRoute
  '/projects/$id/products/$pid': typeof AuthProjectsIdProductsPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/verify': typeof AuthProjectsVerifyRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/projects/$id': typeof AuthProjectsIdIndexRoute
  '/projects/$id/products/$pid': typeof AuthProjectsIdProductsPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/projects/verify': typeof AuthProjectsVerifyRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/projects/$id/': typeof AuthProjectsIdIndexRoute
  '/_auth/projects/$id/products/$pid': typeof AuthProjectsIdProductsPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/verify'
    | '/projects/'
    | '/projects/$id/'
    | '/projects/$id/products/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects/verify'
    | '/projects'
    | '/projects/$id'
    | '/projects/$id/products/$pid'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/projects/verify'
    | '/_auth/projects/'
    | '/_auth/projects/$id/'
    | '/_auth/projects/$id/products/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/verify': {
      id: '/_auth/projects/verify'
      path: '/projects/verify'
      fullPath: '/projects/verify'
      preLoaderRoute: typeof AuthProjectsVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id/': {
      id: '/_auth/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AuthProjectsIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id/products/$pid': {
      id: '/_auth/projects/$id/products/$pid'
      path: '/projects/$id/products/$pid'
      fullPath: '/projects/$id/products/$pid'
      preLoaderRoute: typeof AuthProjectsIdProductsPidRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthProjectsVerifyRoute: typeof AuthProjectsVerifyRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthProjectsIdIndexRoute: typeof AuthProjectsIdIndexRoute
  AuthProjectsIdProductsPidRoute: typeof AuthProjectsIdProductsPidRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProjectsVerifyRoute: AuthProjectsVerifyRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsIdIndexRoute: AuthProjectsIdIndexRoute,
  AuthProjectsIdProductsPidRoute: AuthProjectsIdProductsPidRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
