/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects.index'
import { Route as AuthPhotoIndexRouteImport } from './routes/_auth/photo.index'
import { Route as AuthPhotoIdRouteImport } from './routes/_auth/photo.$id'
import { Route as AuthProjectsIdIndexRouteImport } from './routes/_auth/projects.$id.index'
import { Route as ApiPublicHooksProcessBulkJobsRouteImport } from './routes/api/public/hooks/process-bulk-jobs'
import { Route as AuthProjectsIdVerifyRouteImport } from './routes/_auth/projects.$id.verify'
import { Route as AuthProjectsIdProductsPidRouteImport } from './routes/_auth/projects.$id.products.$pid'
import { Route as AuthProjectsIdProductsPidPreviewRouteImport } from './routes/_auth/projects.$id.products.$pid.preview'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPhotoIndexRoute = AuthPhotoIndexRouteImport.update({
  id: '/photo/',
  path: '/photo/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPhotoIdRoute = AuthPhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIdIndexRoute = AuthProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicHooksProcessBulkJobsRoute =
  ApiPublicHooksProcessBulkJobsRouteImport.update({
    id: '/api/public/hooks/process-bulk-jobs',
    path: '/api/public/hooks/process-bulk-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthProjectsIdVerifyRoute = AuthProjectsIdVerifyRouteImport.update({
  id: '/projects/$id/verify',
  path: '/projects/$id/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIdProductsPidRoute =
  AuthProjectsIdProductsPidRouteImport.update({
    id: '/projects/$id/products/$pid',
    path: '/projects/$id/products/$pid',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProjectsIdProductsPidPreviewRoute =
  AuthProjectsIdProductsPidPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthProjectsIdProductsPidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/photo/$id': typeof AuthPhotoIdRoute
  '/photo/': typeof AuthPhotoIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/projects/$id/verify': typeof AuthProjectsIdVerifyRoute
  '/api/public/hooks/process-bulk-jobs': typeof ApiPublicHooksProcessBulkJobsRoute
  '/projects/$id/': typeof AuthProjectsIdIndexRoute
  '/projects/$id/products/$pid': typeof AuthProjectsIdProductsPidRouteWithChildren
  '/projects/$id/products/$pid/preview': typeof AuthProjectsIdProductsPidPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/photo/$id': typeof AuthPhotoIdRoute
  '/photo': typeof AuthPhotoIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/projects/$id/verify': typeof AuthProjectsIdVerifyRoute
  '/api/public/hooks/process-bulk-jobs': typeof ApiPublicHooksProcessBulkJobsRoute
  '/projects/$id': typeof AuthProjectsIdIndexRoute
  '/projects/$id/products/$pid': typeof AuthProjectsIdProductsPidRouteWithChildren
  '/projects/$id/products/$pid/preview': typeof AuthProjectsIdProductsPidPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/photo/$id': typeof AuthPhotoIdRoute
  '/_auth/photo/': typeof AuthPhotoIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/projects/$id/verify': typeof AuthProjectsIdVerifyRoute
  '/api/public/hooks/process-bulk-jobs': typeof ApiPublicHooksProcessBulkJobsRoute
  '/_auth/projects/$id/': typeof AuthProjectsIdIndexRoute
  '/_auth/projects/$id/products/$pid': typeof AuthProjectsIdProductsPidRouteWithChildren
  '/_auth/projects/$id/products/$pid/preview': typeof AuthProjectsIdProductsPidPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/photo/$id'
    | '/photo/'
    | '/projects/'
    | '/projects/$id/verify'
    | '/api/public/hooks/process-bulk-jobs'
    | '/projects/$id/'
    | '/projects/$id/products/$pid'
    | '/projects/$id/products/$pid/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/photo/$id'
    | '/photo'
    | '/projects'
    | '/projects/$id/verify'
    | '/api/public/hooks/process-bulk-jobs'
    | '/projects/$id'
    | '/projects/$id/products/$pid'
    | '/projects/$id/products/$pid/preview'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/photo/$id'
    | '/_auth/photo/'
    | '/_auth/projects/'
    | '/_auth/projects/$id/verify'
    | '/api/public/hooks/process-bulk-jobs'
    | '/_auth/projects/$id/'
    | '/_auth/projects/$id/products/$pid'
    | '/_auth/projects/$id/products/$pid/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksProcessBulkJobsRoute: typeof ApiPublicHooksProcessBulkJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/photo/': {
      id: '/_auth/photo/'
      path: '/photo'
      fullPath: '/photo/'
      preLoaderRoute: typeof AuthPhotoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/photo/$id': {
      id: '/_auth/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof AuthPhotoIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id/': {
      id: '/_auth/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AuthProjectsIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/hooks/process-bulk-jobs': {
      id: '/api/public/hooks/process-bulk-jobs'
      path: '/api/public/hooks/process-bulk-jobs'
      fullPath: '/api/public/hooks/process-bulk-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessBulkJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects/$id/verify': {
      id: '/_auth/projects/$id/verify'
      path: '/projects/$id/verify'
      fullPath: '/projects/$id/verify'
      preLoaderRoute: typeof AuthProjectsIdVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id/products/$pid': {
      id: '/_auth/projects/$id/products/$pid'
      path: '/projects/$id/products/$pid'
      fullPath: '/projects/$id/products/$pid'
      preLoaderRoute: typeof AuthProjectsIdProductsPidRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id/products/$pid/preview': {
      id: '/_auth/projects/$id/products/$pid/preview'
      path: '/preview'
      fullPath: '/projects/$id/products/$pid/preview'
      preLoaderRoute: typeof AuthProjectsIdProductsPidPreviewRouteImport
      parentRoute: typeof AuthProjectsIdProductsPidRoute
    }
  }
}

interface AuthProjectsIdProductsPidRouteChildren {
  AuthProjectsIdProductsPidPreviewRoute: typeof AuthProjectsIdProductsPidPreviewRoute
}

const AuthProjectsIdProductsPidRouteChildren: AuthProjectsIdProductsPidRouteChildren =
  {
    AuthProjectsIdProductsPidPreviewRoute:
      AuthProjectsIdProductsPidPreviewRoute,
  }

const AuthProjectsIdProductsPidRouteWithChildren =
  AuthProjectsIdProductsPidRoute._addFileChildren(
    AuthProjectsIdProductsPidRouteChildren,
  )

interface AuthRouteChildren {
  AuthPhotoIdRoute: typeof AuthPhotoIdRoute
  AuthPhotoIndexRoute: typeof AuthPhotoIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthProjectsIdVerifyRoute: typeof AuthProjectsIdVerifyRoute
  AuthProjectsIdIndexRoute: typeof AuthProjectsIdIndexRoute
  AuthProjectsIdProductsPidRoute: typeof AuthProjectsIdProductsPidRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPhotoIdRoute: AuthPhotoIdRoute,
  AuthPhotoIndexRoute: AuthPhotoIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsIdVerifyRoute: AuthProjectsIdVerifyRoute,
  AuthProjectsIdIndexRoute: AuthProjectsIdIndexRoute,
  AuthProjectsIdProductsPidRoute: AuthProjectsIdProductsPidRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksProcessBulkJobsRoute: ApiPublicHooksProcessBulkJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
